version: '3.7'

services:

  sample:
    container_name: tic-tac-toe-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/tic-tac-toe-frontend'
      - '/tic-tac-toe-frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true